import { ArrowDownLeft, ArrowUpRight, Download, LockKeyhole, Plus, WalletCards } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { ledger } from "@/lib/platform-data";

export const metadata = { title: "Wallet" };

export default function WalletPage() {
  return <><PageHeading eyebrow="Credit ledger" title="Wallet" description="Every credit is traceable to a purchase, verified play, hold, or audited adjustment." actions={<><button className="button button-secondary"><Download size={17} /> Export statement</button><button className="button button-primary"><Plus size={17} /> Buy credits</button></>} /><section className="wallet-hero"><div><p>Spendable balance</p><strong>1,248.50</strong><span>advertising credits</span></div><div className="wallet-breakdown"><div><span className="wallet-icon earned"><ArrowDownLeft size={19} /></span><p>Earned<strong>684.50 cr</strong></p></div><div><span className="wallet-icon purchased"><WalletCards size={19} /></span><p>Purchased<strong>500.00 cr</strong></p></div><div><span className="wallet-icon promo"><ArrowUpRight size={19} /></span><p>Promotional<strong>64.00 cr</strong></p></div><div><span className="wallet-icon held"><LockKeyhole size={19} /></span><p>Held for campaigns<strong>198.00 cr</strong></p></div></div></section><div className="policy-note"><LockKeyhole size={18} /><div><strong>Immutable double-entry ledger</strong><p>Balances shown here are projections from balanced ledger entries. Settled entries cannot be edited; corrections use linked reversals.</p></div></div><section className="panel table-panel"><div className="panel-header"><div><h2>Credit statement</h2><p>Recent ledger activity across all wallet types</p></div><div className="segmented compact"><button className="selected">All</button><button>Earned</button><button>Spent</button></div></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Description</th><th>Reference</th><th>Wallet</th><th>Amount</th><th>Balance</th></tr></thead><tbody>{ledger.map((entry) => <tr key={`${entry.reference}-${entry.date}`}><td>{entry.date}</td><td><strong>{entry.type}</strong></td><td><code>{entry.reference}</code></td><td>{entry.wallet}</td><td className={entry.positive ? "amount-positive" : "amount-negative"}>{entry.amount}</td><td><strong>{entry.balance}</strong></td></tr>)}</tbody></table></div></section></>;
}
