import { CheckCircle2, Download, Filter, Fingerprint, Search, ShieldAlert, ShieldCheck, XCircle } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { StatusPill } from "@/components/status-pill";
import { evidence } from "@/lib/platform-data";

export const metadata = { title: "Proof of play" };

export default function ProofPage() {
  return <><PageHeading eyebrow="Trust engine" title="Proof of play" description="Inspect how device evidence becomes an accepted, held, or rejected settlement." actions={<button className="button button-secondary"><Download size={17} /> Export evidence</button>} /><section className="proof-summary"><div className="proof-card accepted"><span><CheckCircle2 size={21} /></span><div><strong>98.4%</strong><p>Accepted automatically</p></div></div><div className="proof-card held"><span><ShieldAlert size={21} /></span><div><strong>1.2%</strong><p>Held for review</p></div></div><div className="proof-card rejected"><span><XCircle size={21} /></span><div><strong>0.4%</strong><p>Rejected by policy</p></div></div><div className="proof-card integrity"><span><Fingerprint size={21} /></span><div><strong>100%</strong><p>Signed event batches</p></div></div></section><section className="panel table-panel"><div className="table-tools"><div className="search-box table-search"><Search size={17} /><input aria-label="Search playback evidence" placeholder="Search playback ID, asset, or screen" /></div><button className="button button-secondary"><Filter size={16} /> Filters</button></div><div className="table-scroll"><table><thead><tr><th>Playback</th><th>Advertiser → host</th><th>Asset</th><th>Verified duration</th><th>Received</th><th>Decision</th><th>Settlement</th></tr></thead><tbody>{evidence.map((item) => <tr key={item.id}><td><code>{item.id}</code></td><td><strong>{item.advertiser}</strong><small>to {item.host}</small></td><td>{item.asset}</td><td>{item.duration}</td><td>{item.received}</td><td><StatusPill tone={item.tone}>{item.result}</StatusPill></td><td>{item.credits === "-" ? "Held" : `${item.credits} cr`}</td></tr>)}</tbody></table></div></section><section className="evidence-explainer"><div><ShieldCheck size={24} /><h2>What the server validates</h2><p>A settlement is created only after all required evidence passes the active policy version.</p></div><ol><li><span>1</span><div><strong>Authorized assignment</strong><p>Asset and campaign appear in the device&apos;s signed manifest.</p></div></li><li><span>2</span><div><strong>Ordered evidence</strong><p>Start, checkpoints, and completion have valid sequence and hash-chain links.</p></div></li><li><span>3</span><div><strong>Device confidence</strong><p>Foreground, display, timing, signature, and integrity signals are acceptable.</p></div></li><li><span>4</span><div><strong>Atomic settlement</strong><p>One idempotent transaction debits advertiser and credits host exactly once.</p></div></li></ol></section></>;
}
