import { MapPin, MonitorUp, Plus, RefreshCw, WifiOff } from "lucide-react";
import { PageHeading } from "@/components/page-heading";
import { StatusPill } from "@/components/status-pill";
import { screens } from "@/lib/platform-data";

export const metadata = { title: "Screens" };

export default function ScreensPage() {
  return <><PageHeading eyebrow="Device network" title="Screens" description="Pair devices, monitor playback health, and respond before inventory is lost." actions={<><button className="button button-secondary"><RefreshCw size={17} /> Refresh status</button><button className="button button-primary"><Plus size={17} /> Pair screen</button></>} /><section className="mini-metric-grid"><div><span>Registered screens</span><strong>14</strong><small>Across 9 locations</small></div><div><span>Online now</span><strong className="success-text">12</strong><small>85.7% of network</small></div><div><span>Avg. uptime</span><strong>97.1%</strong><small>Last 30 days</small></div><div><span>Needs action</span><strong className="danger-text">2</strong><small>1 offline, 1 review</small></div></section><section className="panel table-panel"><div className="panel-header"><div><h2>Device inventory</h2><p>Heartbeat status updates every 30-60 seconds during active playback.</p></div></div><div className="table-scroll"><table><thead><tr><th>Screen</th><th>Status</th><th>Now playing</th><th>Last heartbeat</th><th>30-day uptime</th><th>Risk</th><th /></tr></thead><tbody>{screens.map((screen) => <tr key={screen.name}><td><div className="device-name"><span className={`device-thumbnail device-${screen.tone}`}>{screen.status === "Offline" ? <WifiOff size={18} /> : <MonitorUp size={18} />}</span><div><strong>{screen.name}</strong><small><MapPin size={12} /> {screen.location}</small></div></div></td><td><StatusPill tone={screen.tone}>{screen.status}</StatusPill></td><td>{screen.current}</td><td>{screen.heartbeat}</td><td>{screen.uptime}</td><td>{screen.risk}</td><td><button className="text-button">Inspect</button></td></tr>)}</tbody></table></div></section></>;
}
