-- Business peak-hour pricing and isolated advertiser exhaustion.
-- A host venue can define recurring local-time periods where verified ad
-- playback consumes more advertiser credits. Exhaustion is evaluated per
-- advertiser; it never pauses the channel or other campaigns.

create table public.organization_busy_periods (
  id bigint generated by default as identity primary key,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  day_of_week text not null,
  starts_at time not null,
  ends_at time not null,
  consumption_multiplier numeric(5,2) not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint organization_busy_periods_day_valid check (day_of_week in ('mon','tue','wed','thu','fri','sat','sun')),
  constraint organization_busy_periods_time_valid check (ends_at > starts_at),
  constraint organization_busy_periods_multiplier_valid check (consumption_multiplier > 1 and consumption_multiplier <= 10),
  constraint organization_busy_periods_unique unique (organization_id, day_of_week, starts_at, ends_at)
);

create index organization_busy_periods_lookup_idx
  on public.organization_busy_periods (organization_id, day_of_week, starts_at, ends_at);

create trigger organization_busy_periods_set_updated_at before update on public.organization_busy_periods
for each row execute function private.set_updated_at();

alter table public.organization_busy_periods enable row level security;

create policy organization_busy_periods_platform_admin_read
  on public.organization_busy_periods for select to authenticated
  using ((select private.is_platform_admin()));

revoke all on public.organization_busy_periods from public, anon;
grant select on public.organization_busy_periods to authenticated;
grant select on public.organization_busy_periods to service_role;
grant usage, select on sequence public.organization_busy_periods_id_seq to service_role;

create or replace function private.get_business_busy_multiplier(
  p_organization_id bigint,
  p_at timestamptz
)
returns numeric
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(max(period.consumption_multiplier), 1)::numeric
  from public.organizations organization
  left join public.organization_busy_periods period
    on period.organization_id = organization.id
   and period.day_of_week = case extract(isodow from (p_at at time zone organization.operating_time_zone))::integer
     when 1 then 'mon' when 2 then 'tue' when 3 then 'wed' when 4 then 'thu'
     when 5 then 'fri' when 6 then 'sat' else 'sun' end
   and (p_at at time zone organization.operating_time_zone)::time >= period.starts_at
   and (p_at at time zone organization.operating_time_zone)::time < period.ends_at
  where organization.id = p_organization_id
    and period.day_of_week = any(organization.operating_days)
    and (organization.operating_start_date is null or (p_at at time zone organization.operating_time_zone)::date >= organization.operating_start_date)
    and (organization.operating_end_date is null or (p_at at time zone organization.operating_time_zone)::date <= organization.operating_end_date)
    and (p_at at time zone organization.operating_time_zone)::time >= organization.operating_opens_at
    and (p_at at time zone organization.operating_time_zone)::time < organization.operating_closes_at;
$$;

create or replace function private.admin_replace_business_busy_periods(
  p_organization_id bigint,
  p_periods jsonb,
  p_reason text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  before_state jsonb;
begin
  if not (select private.is_platform_admin()) then
    raise insufficient_privilege using message = 'Platform administrator access is required.';
  end if;
  if not exists (select 1 from public.organizations where id = p_organization_id) then
    raise no_data_found using message = 'Business not found.';
  end if;
  if p_reason is null or length(btrim(p_reason)) < 5 or length(p_reason) > 300 then
    raise invalid_parameter_value using message = 'A reason between 5 and 300 characters is required.';
  end if;
  if p_periods is null or jsonb_typeof(p_periods) <> 'array' or jsonb_array_length(p_periods) > 50 then
    raise invalid_parameter_value using message = 'Busy periods must be an array of at most 50 entries.';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(p_periods) as item(day text, "start" text, "end" text, multiplier numeric)
    where item.day is null or item."start" is null or item."end" is null or item.multiplier is null
      or item.day not in ('mon','tue','wed','thu','fri','sat','sun')
      or item."start" !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
      or item."end" !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
      or item."end"::time <= item."start"::time
      or item.multiplier <= 1 or item.multiplier > 10
  ) then
    raise invalid_parameter_value using message = 'One or more busy periods are invalid.';
  end if;
  if exists (
    with periods as (
      select row_number() over () as row_id, item.day, item."start"::time as starts_at, item."end"::time as ends_at
      from jsonb_to_recordset(p_periods) as item(day text, "start" text, "end" text, multiplier numeric)
    )
    select 1 from periods first
    join periods second on second.day = first.day and second.row_id > first.row_id
      and first.starts_at < second.ends_at and second.starts_at < first.ends_at
  ) then
    raise invalid_parameter_value using message = 'Busy periods on the same day cannot overlap.';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object('day', day_of_week, 'start', to_char(starts_at, 'HH24:MI'), 'end', to_char(ends_at, 'HH24:MI'), 'multiplier', consumption_multiplier) order by day_of_week, starts_at), '[]'::jsonb)
  into before_state from public.organization_busy_periods where organization_id = p_organization_id;

  delete from public.organization_busy_periods where organization_id = p_organization_id;
  insert into public.organization_busy_periods (organization_id, day_of_week, starts_at, ends_at, consumption_multiplier, created_by)
  select p_organization_id, item.day, item."start"::time, item."end"::time, item.multiplier, (select auth.uid())
  from jsonb_to_recordset(p_periods) as item(day text, "start" text, "end" text, multiplier numeric);

  insert into public.audit_logs (organization_id, actor_user_id, action, object_type, object_id, reason, before_summary, after_summary)
  values (p_organization_id, (select auth.uid()), 'business.busy_periods.updated', 'organization', p_organization_id::text, p_reason,
    jsonb_build_object('periods', before_state), jsonb_build_object('periods', p_periods));
end;
$$;

create or replace function public.admin_replace_business_busy_periods(
  p_organization_id bigint,
  p_periods jsonb,
  p_reason text
)
returns void
language sql
security invoker
set search_path = ''
as $$
  select private.admin_replace_business_busy_periods(p_organization_id, p_periods, p_reason);
$$;

revoke all on function private.get_business_busy_multiplier(bigint, timestamptz) from public, anon, authenticated;
grant execute on function private.get_business_busy_multiplier(bigint, timestamptz) to service_role;
revoke all on function private.admin_replace_business_busy_periods(bigint, jsonb, text) from public, anon;
revoke all on function public.admin_replace_business_busy_periods(bigint, jsonb, text) from public, anon;
grant execute on function private.admin_replace_business_busy_periods(bigint, jsonb, text) to authenticated;
grant execute on function public.admin_replace_business_busy_periods(bigint, jsonb, text) to authenticated;

-- Replace settlement so the host venue's local busy period multiplies only
-- the advertiser consumption side of an accepted proof event.
create or replace function public.record_stream_viewer_heartbeat_v2(
  p_session_id uuid,
  p_media_public_id uuid,
  p_event_key uuid,
  p_playback_position_seconds numeric,
  p_client_event_at timestamptz,
  p_page_visible boolean,
  p_is_playing boolean
)
returns table (
  validation_result text,
  verified_seconds numeric,
  earned_credits numeric,
  consumed_credits numeric,
  reason_codes text[]
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_session public.stream_viewer_sessions%rowtype;
  target_asset public.media_assets%rowtype;
  host_earning_enabled boolean;
  host_earning_rate numeric(12,6);
  advertiser_consumption_rate numeric(12,6);
  busy_multiplier numeric(5,2) := 1;
  elapsed_seconds numeric(12,3);
  verified_amount numeric(12,3) := 0;
  earned_amount numeric(20,6) := 0;
  consumed_amount numeric(20,6) := 0;
  required_consumption numeric(20,6) := 0;
  available_consumption numeric(20,6) := 0;
  remaining_consumption numeric(20,6) := 0;
  debit_amount numeric(20,6);
  target_transaction_id bigint;
  host_wallet_id bigint;
  platform_wallet_id bigint;
  wallet_record record;
  result_status text := 'accepted';
  result_reasons text[] := '{}';
begin
  if exists (select 1 from public.stream_credit_events event where event.event_key = p_event_key) then
    return query
      select event.validation_result, event.verified_seconds, event.earned_credits,
        event.consumed_credits, event.reason_codes
      from public.stream_credit_events event where event.event_key = p_event_key;
    return;
  end if;

  select * into target_session
  from public.stream_viewer_sessions session
  where session.id = p_session_id
    and session.ended_at is null
    and session.expires_at > now()
  for update;
  if target_session.id is null then
    raise insufficient_privilege using message = 'Viewer session is unavailable';
  end if;

  -- A concurrent request with the same idempotency key may have committed while
  -- this transaction waited for the session lock. Return that result instead of
  -- attempting a duplicate settlement.
  if exists (select 1 from public.stream_credit_events event where event.event_key = p_event_key) then
    return query
      select event.validation_result, event.verified_seconds, event.earned_credits,
        event.consumed_credits, event.reason_codes
      from public.stream_credit_events event where event.event_key = p_event_key;
    return;
  end if;

  select asset.* into target_asset
  from public.media_assets asset
  join public.streaming_channel_items item on item.media_asset_id = asset.id
  where asset.public_id = p_media_public_id
    and item.channel_id = target_session.channel_id
    and item.status = 'active'
    and asset.moderation_status = 'approved'
    and asset.processing_status = 'ready';
  if target_asset.id is null then
    raise check_violation using message = 'Media is not active in this channel';
  end if;

  elapsed_seconds := greatest(0::numeric, extract(epoch from (now() - coalesce(target_session.last_credit_at, target_session.created_at)))::numeric);
  if elapsed_seconds < 10 then
    result_status := 'rejected';
    result_reasons := array['heartbeat_too_soon'];
  elsif elapsed_seconds > 45 then
    result_status := 'rejected';
    result_reasons := array['heartbeat_gap'];
  elsif not p_page_visible or not p_is_playing then
    result_status := 'rejected';
    result_reasons := array['playback_not_visible'];
  elsif p_client_event_at is null or abs(extract(epoch from (now() - p_client_event_at))) > 120 then
    result_status := 'rejected';
    result_reasons := array['client_clock_invalid'];
  elsif p_playback_position_seconds is null or p_playback_position_seconds < 0
    or (target_asset.duration_ms is not null and p_playback_position_seconds > target_asset.duration_ms::numeric / 1000 + 2) then
    result_status := 'rejected';
    result_reasons := array['playback_position_invalid'];
  elsif target_session.last_client_event_at is not null and p_client_event_at <= target_session.last_client_event_at then
    result_status := 'rejected';
    result_reasons := array['client_event_replay'];
  elsif target_session.last_media_asset_id = target_asset.id
    and target_session.last_position_seconds is not null
    and not (
      target_asset.duration_ms is not null
      and target_session.last_position_seconds >= target_asset.duration_ms::numeric / 1000 - 25
      and p_playback_position_seconds <= 25
    )
    and p_playback_position_seconds - target_session.last_position_seconds < greatest(2::numeric, least(elapsed_seconds * 0.5, 8::numeric)) then
    result_status := 'rejected';
    result_reasons := array['playback_not_advancing'];
  else
    verified_amount := least(elapsed_seconds, 20::numeric);
  end if;

  if result_status = 'accepted' then
    select organization.stream_earning_enabled, organization.stream_earning_rate
    into host_earning_enabled, host_earning_rate
    from public.organizations organization where organization.id = target_session.host_organization_id;
    select organization.ad_consumption_rate into advertiser_consumption_rate
    from public.organizations organization where organization.id = target_asset.organization_id;
    if target_session.host_organization_id is not null then
      busy_multiplier := private.get_business_busy_multiplier(target_session.host_organization_id, now());
    end if;

    required_consumption := round((advertiser_consumption_rate * busy_multiplier * verified_amount / 60)::numeric, 6);
    perform wallet.id from public.wallets wallet
    where (wallet.organization_id = target_asset.organization_id and wallet.wallet_type in ('promotional', 'earned', 'purchased'))
       or (wallet.organization_id = target_session.host_organization_id and wallet.wallet_type = 'earned')
       or (wallet.organization_id is null and wallet.wallet_type = 'platform')
    order by wallet.id
    for update;

    select coalesce(sum(greatest(wallet.balance_projection, 0)), 0)
    into available_consumption
    from public.wallets wallet
    where wallet.organization_id = target_asset.organization_id
      and wallet.wallet_type in ('promotional', 'earned', 'purchased');

    if available_consumption < required_consumption then
      result_status := 'insufficient_credit';
      result_reasons := array['advertiser_balance_insufficient'];
      verified_amount := 0;
    else
      consumed_amount := required_consumption;
      earned_amount := case when host_earning_enabled
        then round((host_earning_rate * verified_amount / 60)::numeric, 6)
        else 0 end;
    end if;
  end if;

  if result_status = 'accepted' and (earned_amount > 0 or consumed_amount > 0) then
    select wallet.id into host_wallet_id from public.wallets wallet
      where wallet.organization_id = target_session.host_organization_id and wallet.wallet_type = 'earned';
    select wallet.id into platform_wallet_id from public.wallets wallet
      where wallet.organization_id is null and wallet.wallet_type = 'platform';

    insert into public.ledger_transactions (
      transaction_type, reference_type, reference_id, idempotency_key, status, reason
    ) values (
      'settlement', 'stream_credit_event', p_event_key::text,
      'stream-heartbeat-v2:' || p_event_key::text, 'draft', 'Verified web stream viewing'
    ) returning id into target_transaction_id;

    remaining_consumption := consumed_amount;
    for wallet_record in
      select wallet.id, wallet.balance_projection
      from public.wallets wallet
      where wallet.organization_id = target_asset.organization_id
        and wallet.wallet_type in ('promotional', 'earned', 'purchased')
        and wallet.balance_projection > 0
      order by case wallet.wallet_type when 'promotional' then 1 when 'earned' then 2 else 3 end, wallet.id
    loop
      exit when remaining_consumption <= 0;
      debit_amount := least(wallet_record.balance_projection, remaining_consumption);
      insert into public.ledger_entries (transaction_id, wallet_id, amount, description)
      values (target_transaction_id, wallet_record.id, -debit_amount, 'Advertiser web stream consumption');
      update public.wallets set balance_projection = balance_projection - debit_amount where id = wallet_record.id;
      remaining_consumption := remaining_consumption - debit_amount;
    end loop;
    if consumed_amount > 0 then
      insert into public.ledger_entries (transaction_id, wallet_id, amount, description)
      values (target_transaction_id, platform_wallet_id, consumed_amount, 'Web stream consumption clearing');
      update public.wallets set balance_projection = balance_projection + consumed_amount where id = platform_wallet_id;
    end if;
    if earned_amount > 0 then
      insert into public.ledger_entries (transaction_id, wallet_id, amount, description) values
        (target_transaction_id, host_wallet_id, earned_amount, 'Host web stream earning'),
        (target_transaction_id, platform_wallet_id, -earned_amount, 'Web stream earning clearing');
      update public.wallets set balance_projection = balance_projection + earned_amount where id = host_wallet_id;
      update public.wallets set balance_projection = balance_projection - earned_amount where id = platform_wallet_id;
    end if;
    update public.ledger_transactions set status = 'posted' where id = target_transaction_id;
  end if;

  insert into public.stream_credit_events (
    event_key, viewer_session_id, media_asset_id, host_organization_id,
    advertiser_organization_id, verified_seconds,
    earned_credits, consumed_credits, ledger_transaction_id, validation_result,
    reason_codes, playback_position_seconds, client_event_at, evidence
  ) values (
    p_event_key, target_session.id, target_asset.id, target_session.host_organization_id,
    target_asset.organization_id, verified_amount,
    earned_amount, consumed_amount, target_transaction_id, result_status,
    result_reasons, p_playback_position_seconds, p_client_event_at,
    jsonb_build_object('pageVisible', p_page_visible, 'isPlaying', p_is_playing, 'serverElapsedSeconds', elapsed_seconds, 'busyMultiplier', busy_multiplier, 'baseConsumptionRate', advertiser_consumption_rate)
  );

  update public.stream_viewer_sessions
  set last_activity_at = now(),
      last_credit_at = now(),
      last_media_asset_id = target_asset.id,
      last_position_seconds = p_playback_position_seconds,
      last_client_event_at = p_client_event_at
  where id = target_session.id;

  return query select result_status, verified_amount, earned_amount, consumed_amount, result_reasons;
end;
$$;
